server:
   port: 9100
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka/
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/nguoidung
      username: root
      password: Akthangga1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
