# server:
#    port: 9100
# eureka:
#    client:
#       service-url:
#          default-zone: http://localhost:8761/eureka/
spring:
   datasource:
      url: jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2347601
      username: sql2347601
      password: dS2!aS3%
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: sql2347601
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
