
server:
   port: 8082
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/hinhanh
      username: root
      password: Akthangga1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
   servlet:
      multipart:
         max-file-size: 5MB
         max-request-size: 5MB
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka/
