
spring:
   servlet:
      multipart: 
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
   datasource:
      url: jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2347489
      username: sql2347489
      password: dM2*qG2!
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect

         ##location: ${java.io.tmpdir}


file:
   upload-dir: ./src/main/resources/static/image/
   

# server:
#    port: 8082
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
databaseName: sql10346568
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80

   

