# server:
#    port: 8085
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2348046
      username: sql2348046
      password: aK8!rI2*
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
# eureka:
#    client:
#       service-url:
#          default-zone: http://localhost:8761/eureka/
databaseName: sql2348046
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
