server:
   port: 8081
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/khuyenmai
      username: root
      password: Akthangga1
