server:
   port: 8081
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/khuyenmai
      username: root
      password: Akthangga1
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka/
