
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
#server:
#port: 8082
spring:
   datasource:
      url: jdbc:mysql:// sql10.freemysqlhosting.net:3306/sql10346568
      username: sql10346568
      password: nWBlJJ6eHG
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
   client:
      service-url:
#          default-zone: http://localhost:8761/eureka/
           default-zone: https://servergiay.herokuapp.com/eureka/
   instance:
      preferIpAddress: false
      hostname:  ${APPLICATION_DOMAIN}
databaseName: sql10346568
